//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KahveMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class iletisimformu
    {
        public int id { get; set; }

        [Display(Name = "Adýnýz Soyadýnýz")]
        [Required(ErrorMessage = "Lütfen Adýnýzý ve Soyadýnýz giriniz!")]
        public string adSoyad { get; set; }

        [Required(ErrorMessage = "Lütfen mail adresinizi giriniz!")]
        [Display(Name = "Eposta adresiniz")]
        [EmailAddress(ErrorMessage = "Lütfen geçerli bir mail adresi giriniz!")]
        public string eposta { get; set; }

        [Required(ErrorMessage = "Lütfen mesajýnýzý giriniz!")]
        [Display(Name = "Mesajýnýzý yazýnýz")]
        public string mesaj { get; set; }

        public bool izin { get; set; }

        [Required(ErrorMessage = "Lütfen cinsiyetinizi belirtiniz!")]
        [Display(Name = "Cinsiyetiniz")]
        public bool cinsiyet { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    }
}
