//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KahveMVC.Models.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kahve2019Entities : DbContext
    {
        public kahve2019Entities()
            : base("name=kahve2019Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<anasayfa> anasayfa { get; set; }
        public DbSet<hakkimizda> hakkimizda { get; set; }
        public DbSet<magaza> magaza { get; set; }
        public DbSet<magazasaat> magazasaat { get; set; }
        public DbSet<kullanici> kullanici { get; set; }
        public DbSet<iletisimformu> iletisimformu { get; set; }
        public DbSet<urunler> urunler { get; set; }
    }
}
