//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KahveMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class kullanici
    {
        public int id { get; set; }

        [Display(Name = "Kullanýcý Adý")]
        [Required(ErrorMessage = "Lütfen kullanýcý adýnýzý giriniz!")]
        public string ad { get; set; }

        [Display(Name = "Parola")]
        [Required(ErrorMessage = "Lütfen parolanýzý giriniz!")]
        public string sifre { get; set; }

        public virtual bool BeniHatirla { get; set; }
    }
}
