//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KahveMVC.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;
    
    public partial class urunler
    {
        public int id { get; set; }

        public virtual HttpPostedFileBase fotoFile { get; set; }

        public string foto { get; set; }

        [Required]
        [Display(Name = "Baþlýk")]
        public string baslik { get; set; }

        [Required]
        [Display(Name = "Üst Baþlýk")]
        public string ustBaslik { get; set; }

        [AllowHtml]
        [Required]
        [Display(Name = "Ýçerik")]
        public string icerik { get; set; }

        public bool aktif { get; set; }

        [Required]
        [Display(Name = "Sýra")]
        public int sira { get; set; }
    }
}
